import { defineAuthLocale } from '@better-auth-ui/core'

// better-auth-ui 官方 locales 包暂无中文，此处提供完整的简体中文映射。
// 用法：<AuthProvider locale={... zhCN} />，随 app 本身的中英文切换而切换。
export const zhCN = defineAuthLocale({
  languageTag: 'zh-CN',
  direction: 'ltr',
  localization: {
    auth: {
      callbackAccountLinkedTitle: '账号已关联',
      callbackAccountLinkedDescription: '你的账号已连接成功。',
      callbackAccountLinkConflictTitle: '该账号已被关联',
      callbackAccountLinkConflictDescription:
        '该第三方账号属于其他用户，或无法安全关联。',
      callbackCancelledTitle: '验证已取消',
      callbackCancelledDescription: '未做任何更改，随时可以重试。',
      callbackFailedTitle: '未能完成验证',
      callbackFailedDescription: '回调校验失败，请返回登录重试。',
      callbackContinue: '继续',
      callbackEmailVerifiedTitle: '邮箱已验证',
      callbackEmailVerifiedDescription:
        '邮箱地址验证通过，可以继续使用账号。',
      callbackEmailNotVerifiedTitle: '请先验证邮箱',
      callbackEmailNotVerifiedDescription:
        '登录前请先查收邮件中的验证链接。',
      callbackExpiredLinkTitle: '链接已过期',
      callbackExpiredLinkDescription:
        '请重新申请链接，并使用收件箱里最新的一封。',
      callbackGenericErrorTitle: '出错了',
      callbackGenericErrorDescription: '未能完成此次请求，请返回登录重试。',
      callbackGenericSuccessTitle: '已完成',
      callbackGenericSuccessDescription: '验证已成功完成。',
      callbackMissingEmailTitle: '未获取到邮箱地址',
      callbackMissingEmailDescription:
        '第三方未提供邮箱地址，请换一种登录方式。',
      callbackPasswordResetTitle: '密码已重置',
      callbackPasswordResetDescription: '请使用新密码登录。',
      callbackSignupCompleteTitle: '账号已创建',
      callbackSignupCompleteDescription: '账号已就绪，可以继续使用。',
      callbackSignupDisabledTitle: '暂不支持注册',
      callbackSignupDisabledDescription:
        '该方式不能创建新账号，请直接登录。',
      callbackViewAccountSettings: '账号设置',
      account: '账号',
      alreadyHaveAnAccount: '已有账号？',
      alreadyVerifiedYourEmail: '邮箱已经验证过了？',
      confirmPassword: '确认密码',
      confirmPasswordPlaceholder: '请再次输入密码',
      checkYourEmail: '请查收邮件中的验证链接',
      checkYourEmailTitle: '查收邮件',
      continueWith: '使用 {{provider}} 继续',
      email: '邮箱',
      emailPlaceholder: 'm@example.com',
      fieldRequired: '该字段必填',
      forgotPassword: '忘记密码',
      forgotPasswordLink: '忘记密码？',
      hidePassword: '隐藏密码',
      invalidEmail: '请输入有效的邮箱地址',
      invalidResetPasswordToken: '重置密码的令牌无效',
      name: '姓名',
      namePlaceholder: '姓名',
      needToCreateAnAccount: '还没有账号？',
      newPassword: '新密码',
      newPasswordPlaceholder: '新密码',
      openEmailProvider: '打开 {{provider}}',
      or: '或',
      optional: '（可选）',
      password: '密码',
      passwordCompromised:
        '该密码曾在数据泄露中出现过，请换一个。',
      passwordFair: '一般',
      passwordGood: '不错',
      passwordPlaceholder: '密码',
      passwordResetEmailSent: '密码重置邮件已发送',
      passwordResetErrorDescription: '密码重置失败，请重试。',
      passwordResetSuccess: '密码重置成功',
      passwordResetSuccessDescription:
        '密码重置成功，请使用新密码登录。',
      passwordStrength: '密码强度',
      passwordStrong: '强',
      passwordWeak: '弱',
      passwordsDoNotMatch: '两次输入的密码不一致',
      rememberMe: '记住我',
      tooLong: '最多 {{max}} 个字符',
      tooShort: '至少 {{min}} 个字符',
      rememberYourPassword: '还记得密码？',
      resend: '重新发送',
      resendIn: '{{seconds}}s 后重发',
      resetLinkSentTo: '已向 {{email}} 发送密码重置链接',
      resetPassword: '重置密码',
      sendResetLink: '发送重置链接',
      scanToOpenEmailProvider: '扫码在手机上打开 {{provider}}',
      showPassword: '显示密码',
      signIn: '登录',
      signOut: '退出登录',
      signUp: '注册',
      verificationEmailSent: '验证邮件已发送！',
      verifyEmail: '验证邮箱',
    },
    settings: {
      account: '账号',
      accountUnlinked: '账号已解绑',
      active: '有效',
      activeSessions: '活跃会话',
      reauthenticationTitle: '重新登录',
      reauthenticationDescription:
        '继续之前请重新登录，以确认是你本人。',
      reauthenticationAction: '重新登录',
      avatar: '头像',
      currentSession: '当前会话',
      avatarChangedSuccess: '头像更换成功',
      avatarDeletedSuccess: '头像删除成功',
      changeAvatar: '更换头像',
      deleteAvatar: '删除头像',
      link: '关联',
      linkedAccounts: '已关联账号',
      lastAccountUnlinkingDisabled: '解绑前请先关联另一种登录方式。',
      linkProvider: '关联你的 {{provider}} 账号',
      cancel: '取消',
      copyToClipboard: '复制到剪贴板',
      copiedToClipboard: '已复制到剪贴板',
      changeEmail: '更换邮箱',
      changeEmailSuccess: '请查收邮件以确认更换',
      changePassword: '修改密码',
      changePasswordSuccess: '密码修改成功',
      currentPassword: '当前密码',
      currentPasswordPlaceholder: '请输入当前密码',
      dangerZone: '危险区',
      delete: '删除',
      optional: '可选',
      profileUpdatedSuccess: '资料更新成功',
      revoke: '撤销',
      revokeSession: '撤销会话',
      revokeSessionSuccess: '会话撤销成功',
      signOutOtherDevices: '退出其他设备',
      signOutOtherDevicesDescription: '将退出除本设备之外的所有设备。',
      signOutOtherDevicesSuccess: '其他设备已退出成功',
      signOutEverywhere: '退出所有设备',
      signOutEverywhereDescription: '将退出本设备及所有其他设备。',
      saveChanges: '保存修改',
      setPassword: '设置密码',
      setPasswordDescription:
        '你还没有设置密码，可以申请重置链接来设置。',
      security: '安全',
      settings: '设置',
      time: '时间',
      unlinkProvider: '解绑 {{provider}}',
      updateEmail: '更新邮箱',
      updatePassword: '更新密码',
      uploadAvatar: '上传头像',
      userProfile: '个人资料',
    },
  },
})
