/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteRouteImport } from './routes/dashboard/route'
import { Route as AuthPathRouteImport } from './routes/auth/$path'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardConfigRouteImport } from './routes/dashboard/config'
import { Route as DashboardNodeUsersRouteImport } from './routes/dashboard/node-users'
import { Route as DashboardNodesRouteImport } from './routes/dashboard/nodes'
import { Route as DashboardTrafficRouteImport } from './routes/dashboard/traffic'
import { Route as DashboardSettingsPathRouteImport } from './routes/dashboard/settings/$path'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRouteRoute = DashboardRouteRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPathRoute = AuthPathRouteImport.update({
  id: '/auth/$path',
  path: '/auth/$path',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardConfigRoute = DashboardConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNodeUsersRoute = DashboardNodeUsersRouteImport.update({
  id: '/node-users',
  path: '/node-users',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardNodesRoute = DashboardNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardTrafficRoute = DashboardTrafficRouteImport.update({
  id: '/traffic',
  path: '/traffic',
  getParentRoute: () => DashboardRouteRoute,
} as any)
const DashboardSettingsPathRoute = DashboardSettingsPathRouteImport.update({
  id: '/settings/$path',
  path: '/settings/$path',
  getParentRoute: () => DashboardRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/$path': typeof AuthPathRoute
  '/dashboard/config': typeof DashboardConfigRoute
  '/dashboard/node-users': typeof DashboardNodeUsersRoute
  '/dashboard/nodes': typeof DashboardNodesRoute
  '/dashboard/traffic': typeof DashboardTrafficRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/$path': typeof DashboardSettingsPathRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth/$path': typeof AuthPathRoute
  '/dashboard/config': typeof DashboardConfigRoute
  '/dashboard/node-users': typeof DashboardNodeUsersRoute
  '/dashboard/nodes': typeof DashboardNodesRoute
  '/dashboard/traffic': typeof DashboardTrafficRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/settings/$path': typeof DashboardSettingsPathRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth/$path': typeof AuthPathRoute
  '/dashboard/config': typeof DashboardConfigRoute
  '/dashboard/node-users': typeof DashboardNodeUsersRoute
  '/dashboard/nodes': typeof DashboardNodesRoute
  '/dashboard/traffic': typeof DashboardTrafficRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/$path': typeof DashboardSettingsPathRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/about'
    | '/auth/$path'
    | '/dashboard/config'
    | '/dashboard/node-users'
    | '/dashboard/nodes'
    | '/dashboard/traffic'
    | '/dashboard/'
    | '/dashboard/settings/$path'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth/$path'
    | '/dashboard/config'
    | '/dashboard/node-users'
    | '/dashboard/nodes'
    | '/dashboard/traffic'
    | '/dashboard'
    | '/dashboard/settings/$path'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/about'
    | '/auth/$path'
    | '/dashboard/config'
    | '/dashboard/node-users'
    | '/dashboard/nodes'
    | '/dashboard/traffic'
    | '/dashboard/'
    | '/dashboard/settings/$path'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRouteRoute: typeof DashboardRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthPathRoute: typeof AuthPathRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/$path': {
      id: '/auth/$path'
      path: '/auth/$path'
      fullPath: '/auth/$path'
      preLoaderRoute: typeof AuthPathRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/config': {
      id: '/dashboard/config'
      path: '/config'
      fullPath: '/dashboard/config'
      preLoaderRoute: typeof DashboardConfigRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/node-users': {
      id: '/dashboard/node-users'
      path: '/node-users'
      fullPath: '/dashboard/node-users'
      preLoaderRoute: typeof DashboardNodeUsersRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/nodes': {
      id: '/dashboard/nodes'
      path: '/nodes'
      fullPath: '/dashboard/nodes'
      preLoaderRoute: typeof DashboardNodesRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/traffic': {
      id: '/dashboard/traffic'
      path: '/traffic'
      fullPath: '/dashboard/traffic'
      preLoaderRoute: typeof DashboardTrafficRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
    '/dashboard/settings/$path': {
      id: '/dashboard/settings/$path'
      path: '/settings/$path'
      fullPath: '/dashboard/settings/$path'
      preLoaderRoute: typeof DashboardSettingsPathRouteImport
      parentRoute: typeof DashboardRouteRoute
    }
  }
}

interface DashboardRouteRouteChildren {
  DashboardConfigRoute: typeof DashboardConfigRoute
  DashboardNodeUsersRoute: typeof DashboardNodeUsersRoute
  DashboardNodesRoute: typeof DashboardNodesRoute
  DashboardTrafficRoute: typeof DashboardTrafficRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  DashboardSettingsPathRoute: typeof DashboardSettingsPathRoute
}

const DashboardRouteRouteChildren: DashboardRouteRouteChildren = {
  DashboardConfigRoute: DashboardConfigRoute,
  DashboardNodeUsersRoute: DashboardNodeUsersRoute,
  DashboardNodesRoute: DashboardNodesRoute,
  DashboardTrafficRoute: DashboardTrafficRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  DashboardSettingsPathRoute: DashboardSettingsPathRoute,
}

const DashboardRouteRouteWithChildren = DashboardRouteRoute._addFileChildren(
  DashboardRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRouteRoute: DashboardRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthPathRoute: AuthPathRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
